services:
  search-home:
    image: theysh0303/search-home:latest
    container_name: search-home
    ports:
      - "${PORT:-39421}:${PORT:-39421}"
    restart: unless-stopped
    environment:
      PORT: "${PORT:-39421}"
      COS_BUCKET: "${COS_BUCKET:-}"
      COS_REGION: "${COS_REGION:-}"
      COS_BASE_URL: "${COS_BASE_URL:-}"
      COS_SECRET_ID: "${COS_SECRET_ID:-}"
      COS_SECRET_KEY: "${COS_SECRET_KEY:-}"
      COS_STYLE_DISPLAY: "${COS_STYLE_DISPLAY:-imageMogr2/auto-orient/thumbnail/1920x>/format/jpg/interlace/1}"
      COS_STYLE_THUMB: "${COS_STYLE_THUMB:-imageMogr2/auto-orient/thumbnail/360x>/format/jpg/interlace/1}"
    volumes:
      - ./uploads:/app/uploads
      - ./links.json:/app/links.json
      - ./background.json:/app/background.json
      - ./images.json:/app/images.json
